### ISSUE TITLE
not working on udemy business account with a scholorship

### ISSUE THREAD

**Issue by nivethan-me** [huybn5776/udemy-seeks#1]
hi can you make your extension work on this following url too?
https://colonline.udemy.com/course/the-complete-javascript-course/learn/lecture/22649543#questions/15708516
it will be very helpful to me and many others as well, thanks in advance 😃

**Comment by huybn5776** [comment]
It look like it can be done by add `"*://colonline.udemy.com/course/*"` to matches array of [manifest.json](https://github.com/huybn5776/udemy-seeks/blob/main/public/manifest.json). 
But i didn't have access right to udemy business, can you test it for me? thanks.

Open extensions page, drop this updated extension package to install it.
[udemy_seeks-1.0.8.zip](https://github.com/huybn5776/udemy-seeks/files/7149690/udemy_seeks-1.0.8.zip)

I think you may found error when getting lecture data, because it's using api `https://www.udemy.com/api-2.0/...` but `https://some-domain.udemy.com/api-2.0/...`. In implementation, this api is need for this extension to get lecture captions.

**Comment by nivethan-me** [comment]
i downloaded the zip but how can i install it? i could find any .xpi files there!  i also tried to swap the manifest.json file in the firefox folder but i also couldn't find that file too

**Comment by huybn5776** [comment]
Yes it's an zip, drop it into your extensions page (about:addons for firefox), it should show a message to ask you to install.
I'm using Firefox Developer Edition, you may also need to disable extension signing on about:config page `xpinstall.signatures.required`

**Comment by nivethan-me** [comment]
it says this addon could not be installed because  it appears to be corrupt.

**Comment by huybn5776** [comment]
New version submitted, you can [update it from here](https://addons.mozilla.org/zh-TW/firefox/addon/udemy-seeks/) and test if it work.

**Comment by nivethan-me** [comment]
![udemy-seek-error](https://user-images.githubusercontent.com/63112138/132992802-442e88f9-a15c-45ad-ab77-21425b4a00b0.png)

when i press the extension icon it says fetching lecture data and caption but it's not working,
 i took the ss with console so you can see the errors.

**Comment by huybn5776** [comment]
Did you seen any console message from `content-script.js`?  Also please click extension icon on toolbar to check its state is running or loading.

**Comment by nivethan-me** [comment]
i checked again but no messages from content-script.js and as i said extension toolbar says fetching lecture data and caption
![udemy2](https://user-images.githubusercontent.com/63112138/132993360-b1090f81-45d3-4919-946f-dc167f6f5c17.png)

**Comment by huybn5776** [comment]
I have to try it on your environment, but I don't think keep submit and bumping the version of extension is a good idea. Can you try to find a way to install extension from zip [like this](https://stackoverflow.com/questions/62237202)?

This version use `window.location.host` as api url, if you figure out how to install please try it. Or you can also download <s>Chrome</s> Brave browser to try it.
[udemy_seeks-1.0.8.zip](https://github.com/huybn5776/udemy-seeks/files/7149853/udemy_seeks-1.0.8.zip)

**Comment by huybn5776** [comment]
I have found a way to generate .xpi file for self distribution, this is an zip file containing .xpi
[udemy_seeks-1.0.9-an+fx.xpi.zip](https://github.com/huybn5776/udemy-seeks/files/7161061/udemy_seeks-1.0.9-an%2Bfx.xpi.zip)

**Comment by nivethan-me** [comment]
i have installed it but still no luck! anyway i exported all the console errors and messages in this following file!

[console-export-2021-9-14_20-28-28.txt](https://github.com/huybn5776/udemy-seeks/files/7162993/console-export-2021-9-14_20-28-28.txt)

**Comment by huybn5776** [comment]
Ok, I have put more console.log into it, hope it can get some more detail of it.
Please also told me the extension state when click extension icon on toolbar.
[udemy_seeks-1.0.93-an+fx.xpi.zip](https://github.com/huybn5776/udemy-seeks/files/7163251/udemy_seeks-1.0.93-an%2Bfx.xpi.zip)

**Comment by huybn5776** [comment]
Close due to inactivity. Feel free to reopen, if someone wanna try business udemy or implement by himself and open an PR.
